### ISSUE TITLE
Support for `.jshintrc` configuration file

### ISSUE THREAD

**Issue by olliebennett** [damian/jshint#24]
Would it be possible to support the JSON-formatted `.jshintrc` configuration file ([example](https://github.com/jshint/jshint/blob/master/.jshintrc)) instead of requiring a `jshint.yml`? I would say the `.jshintrc` (JSON) format is the norm outside the Rails community, and while I understand that YML fits well in Rails, the different format means maintaining duplicate copies of the same configuration (i.e. JSON + YML). Some other tools (for example IDEs or CI systems) may only support the `.jshintrc` configuration.

Would this be feasible for inclusion in this project? I'm not sure to what extent the included JSHint library itself could parse and process this format of configuration file without external JSON-parsing dependencies for the gem.

The following error appears when no `jshint.yml` file is present.

```
ruby/gems/2.2.0/gems/jshint-1.3.1/lib/jshint/configuration.rb:86:in `initialize': No such file or directory @ rb_sysopen - /path/to/repo/config/jshint.yml (Errno::ENOENT)
```

**Comment by threedaymonk** [comment]
I took a brief look at this. There's already JSON loading/parsing support in the dependencies, and it's relatively easy to tweak the `Configuration` class to load from JSON.

However, a bigger problem is that `.jshintrc` doesn't contain all the information needed: it's essentially just the `options` part of `jshint.yml`, and doesn't say which files should be checked. You can set `files` to a sensible default of `**/*.js`, but I think that might be too limiting in practice.

I suspect that a better solution might be to give `jshint.yml` a key that specifies a (relative) path for a JSON file from which it can load its options, i.e.:

```yaml
files: ["**/*.js"]
exclude_paths: []
options_file: "../.jshintrc"
```

The final problem is that many `.jshintrc` files in the wild contain comments, which make them valid JavaScript but invalid JSON, but that's fixed by not doing that!

**Comment by olliebennett** [comment]
I agree an `options_file` key would make sense as well as being backwards-compatible.

My original thought (which I don't think is as good as yours) was that we could inherit options from the `.jshintrc` file, and overwrite them with options (if any) specified in the `jshint.yml` file. I thought it would logically follow that we should traverse up the directory tree to find the `.jshintrc` file (or just look in the same location as `jshint.yml`).

Regarding your point about `.jshintrc` files containing comments - don't think it's a big issue to fail parsing when comments are found, if JSHint can't correctly parse the `.jshintrc` file internally. Would be a shame to have to introduce code/dependencies to strip those comments.

**Comment by damian** [comment]
@olliebennett - @threedaymonk is right. This gem requires more information than just the JSHint options provided in `.jshintrc`. I'm personally not a fan of having gem configurations scattered across multiple files either, as it means that we first have to be able to parse these options, and also manage how they are resolved. Because of this, I'm less inclined to start looking in to this issue.

Would it not be possible for you to convert your `.jshintrc` in to the YAML notation(it might take a few minutes tops).

**Comment by olliebennett** [comment]
Yep - I understand that additional options are present in the `jshint.yml`, and also appreciate your other concerns.

In my case (and I should have explained my use case better), I can't remove the `.jshintrc` because that's used by a JSHint plugin in my text editor. I want the editor to flag the same JSHint offenses as will be picked up by this gem (during CI). My current workaround is to manually keep the `.jshintrc` and `jshint.yml` options in sync.

Thanks for the consideration, anyway.

**Comment by damian** [comment]
I see. If your editor is already capable of doing this / linting is there any need to use this gem?

**Comment by olliebennett** [comment]
Yep - the gem is used during Continuous Integration (by [Wercker](http://wercker.com/), in our case), so that no members of the team are able to push invalid/un-linted code into production^. For example, these developers may not have noticed the errors flagged by their editors (or their editors may not even be configured for auto-linting).

^ Your gem is very useful in fulfilling this purpose (so thanks!).

**Comment by threedaymonk** [comment]
@olliebennett The best solution for you might be to generate `.jshintrc` automatically by scripting something like this:

```sh
$ ruby -ryaml -rjson -e'puts JSON.pretty_generate(YAML.load(ARGF)["options"])' \
< config/jshint.yml > .jshintrc
```

You could put that in a script or a `Rakefile` or a git hook, depending on your workflow.

**Comment by olliebennett** [comment]
Thanks @threedaymonk. Think I've been persuaded that this isn't something worth including in the gem! Cheers both for your input.
